#! /bin/bash
TEXTDOMAINDIR=./
TEXTDOMAIN=mps-gtk

# path mps-baslat.sh
path=./

IMMAGINE=/usr/share/icons/mps-gtk.png

UPDATE="$path/mps-baslat.sh 1"
UPGRADE="$path/mps-baslat.sh 2"
FORCE="$path/mps-baslat.sh 3"
INSTPAC="$path/mps-baslat.sh 4"
UPPACK="$path/mps-baslat.sh 10"
REMOVE="$path/mps-baslat.sh 5"
SEARCH="$path/mps-baslat.sh 6"
SEARCHINSTALL="$path/mps-baslat.sh 7"
BELONG="$path/mps-baslat.sh 8"
INFOPAC="$path/mps-baslat.sh 9"
DIPENDENZEINUTILI="$path/mps-baslat.sh 11"
CACHE="$path/mps-baslat.sh 12"
PACDIFF="$path/mps-baslat.sh 13"
DBUPGRADE="$path/mps-baslat.sh 14"
OPTIMIZE="$path/mps-baslat.sh 15"
INFO="$path/mps-baslat.sh 16"

SYNAPTIC=/usr/local/bin/xlm-synaptic.sh

export TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN=mps-gtk

export MAIN_DIALOG='
<window title="Milis Program Ekle-Kaldır"  window_position="1">
 <vbox>
<pixmap><input file>'$IMMAGINE'</input></pixmap>
<text><label>'$(gettext 'MPS Uzantılı Uygulama Dosyalarını Kur')'</label></text>
<hbox>
<frame>
<button><input file icon="gtk-refresh"></input>
<label>'$(gettext 'Talimat Güncelle')'</label>
<action signal="clicked">'$UPDATE' &</action></button>
<button><input file icon="gtk-refresh"></input>
<label>'$(gettext 'Sistemi Güncelle')'</label>
<action signal="clicked">'$UPGRADE' &</action></button>
<button>
<input file icon="gtk-dialog-warning"></input>
<label>'$(gettext 'Gerekleriyle Kaldır')'</label>
<action signal="clicked">'$FORCE' &</action>
</button>
<button>
<input file icon="redo"></input>
<label>'$(gettext 'Program Kur')'</label>
<action signal="clicked">'$INSTPAC' &</action>
</button>
<button>
<input file icon="gtk-remove"></input>
<label>'$(gettext 'Program Sil')'</label>
<action>'$REMOVE' &</action></button>
</frame>
<frame>
<button><input file icon="search"></input>
<label>'$(gettext 'Program Bul')'</label>
<action signal="clicked">'$SEARCH' &</action></button>
<button><input file icon="redo"></input>
<label>'$(gettext 'Derle & Kur')'</label>
<action signal="clicked">'$SEARCHINSTALL' &</action></button>
<button>
<input file icon="redo"></input>
<label>'$(gettext 'Yeniden Kur')'</label>
<action signal="clicked">'$BELONG' &</action>
</button>
<button>
<input file icon="gtk-dialog-info"></input>
<label>'$(gettext 'Paket Bilgisi')'</label>
<action>'$INFOPAC' &</action></button>
<button>
<input file icon="redo"></input>
<label>'$(gettext 'Bilgisayardan Program Kur')'</label>
<action>'$UPPACK' &</action></button>
</frame>
<frame>
<button><input file icon="gtk-clear"></input>
<label>'$(gettext 'Gereksizleri Kaldır')'</label>
<action signal="clicked">'$DIPENDENZEINUTILI' &</action>
</button>
<button>
<input file icon="gtk-clear"></input>
<label>'$(gettext 'Kaynak Temizle')'</label>
<action>'$CACHE' &</action></button>
<button>
<input file icon="gtk-clear"></input>
<label>Depo Temizle</label>
<action>'$PACDIFF' &</action></button>
<button>
<input file icon="gtk-refresh"></input>
<label>MPS vt Güncelle</label>
<action>'$DBUPGRADE' &</action></button>
<button>
<input file icon="gtk-refresh"></input>
<label>'$(gettext 'MPS Onar')'</label>
<action>'$OPTIMIZE' &</action></button>
</frame>
</hbox>
<frame>
<button>
<width>24</width>
<input file icon="gtk-dialog-info"></input>
<label>İnternet Adresimiz</label>
<action signal="clicked">xdg-open "https://www.milislinux.org"</action>
</button>
<button>
<input file icon="search"></input>
<label>'$(gettext 'MiLPek Uygulamasını Aç')'</label>
<action>milpek &</action>
</button>
</frame>
<hbox>
<button>
<input file icon="gtk-dialog-info"></input>
<label>Bilgi</label>
<action signal="clicked">'$INFO' &</action>
</button>
<button>
<label>'$(gettext 'Çıkış')'</label>
<input file icon="editdelete"></input>
<action type="Exit">exit 0</action>
</button>
</hbox>
</vbox>
</window>
'

gtkdialog --program=MAIN_DIALOG
